### ISSUE TITLE
regression: event header can't be copied with normal Python syntax.

### ISSUE THREAD

**Issue by kdart-brt** [python-hyper/h11#112]
I have been using h11 for a while now. In my code, I made a copy of the headers like this:

```python
headers = ev.headers[:]
```

That is the normal way to copy a list (headers was a list). 

Now, after an update, it does this:
ValueError: too many values to unpack (expected 3)

in debugger, the same:
1:Debug:1/2> ev.headers[:]
*** ValueError: too many values to unpack (expected 3)

Something changed in the `headers` attrbibute. It also does not have a `copy` method.
1:Debug:1/2> ev.headers.copy()
*** AttributeError: 'Headers' object has no attribute 'copy'

**Comment by pquentin** [comment]
@kdart-brt The way headers work has changed with https://github.com/python-hyper/h11/pull/104 which was released recently

**Comment by tomchristie** [comment]
Right, so the intent was not to cause any regressions in how we approached #104, but that's obviously not *quite* been the case here, since you've found a wrinkle.

The change here is that the requirement in #104, of "allow h11 to expose the original header casing" meant that we've needed to change headers from a *list* to a *sequence-like* interface in the 0.11 release.

There's two options for us here:

* Issue an amendment in https://h11.readthedocs.io/en/latest/changes.html#v0-11-0-2020-10-05 to make that explicit.
* Change the `Headers` data structure so that we're ensuring it has a *fully* list-like interface, rather than simple a *sequence* interface.

Of those two I'd probably tend towards the first.

From a user POV that'd mean using the following if you want a list-copy of the structure...

```python
headers = list(ev.headers)
```

**Comment by kdart-brt** [comment]
That alternate list constructor works. So, whatever you do is fine by me.

**Comment by pquentin** [comment]
👍 on the simple amendment

**Comment by kdart-brt** [comment]
BTW, thanks for the help.

**Comment by tomchristie** [comment]
You're very welcome. 💛

**Comment by pgjones** [comment]
Does #125 help this?

**Comment by tomchristie** [comment]
> Does https://github.com/python-hyper/h11/pull/125 help this?

Yes.
