### ISSUE TITLE
pep8 examples please

### ISSUE THREAD

**Issue by dimaqq** [python-hyper/h11#28]

**Comment by sigmavirus24** [comment]
What is this even about?

**Comment by dimaqq** [comment]
Sorry for shorthand, I meant please adjust `examples/curio-server.py`, etc. to pep8 style...
Then again I can just make a PR...

**Comment by njsmith** [comment]
```shell
~/h11$ flake8 examples/curio-server.py      
~/h11$ 
```
?

I mean, PRs that improve code readability certainly welcome. If it's PEP 8 compliant as well then even better ;-)

**Comment by dimaqq** [comment]
I'm using pyflakes/flake8/pep8 stack, I'm working on basic cleanup, which is mostly inserting blank lines.

There are other style concerns that I would perhaps first discuss here, for example:

```
if (foo and bar and baz
    or qux and quux and quuux):
    frob(foo)
    frob(bar)
```

A couple of concerns here: position of `or` (wrt conditions) and position of `or` (wrt code block)

(wrt conditions) style checker complains about "new lines before `or`" which in itself is not terrible — I totally get your logic, even if I would've picked another layout.

(wrt code block) Python devs care about indentation and this example has `or` and `frob` starting on the same level. It's confusing. Style checker is able to report that, but for now it's masked by "new line before `or`".

**Comment by njsmith** [comment]
The thing about putting `or` before the line break is a bug in pycodestyle – PEP 8 used to recommend the former, but recently switched to recommending the latter (because [Knuth says so](https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator)).

The thing about starting on the same level is definitely an annoying Python quirk with few good solutions. What I've started doing recently is writing it like:
```python
if (foo and bar and baz
      or qux and quux and quuux):
    frob(foo)
    frob(bar)
```
This also freaks out pycodestyle, but AFAICT there is actually literally no way to write this code that doesn't freak out pycodestyle (it has 3 rules that say the continuation line must be indented 4 spaces, that the if body must be indented 4 spaces, and that the continuation line and body must have different indentations, so...). If you read PEP 8, it specifically says that it *allows* the `or` and `frob` to have the same indentation. The fact that pycodestyle makes up rules like this that aren't actually in PEP 8 is one of the reasons why Guido got grumpy at them and the program is now called "pycodestyle" instead of "pep8" :-).
