### ISSUE TITLE
RemoteProtocolError when an expecting client bails out

### ISSUE THREAD

**Issue by vfaronov** [python-hyper/h11#43]
We get a request with `Expect: 100-continue`, like those that curl is known for sending:

```
import h11
conn = h11.Connection(our_role=h11.SERVER)
conn.receive_data(b'POST / HTTP/1.1\r\n'
                  b'Host: example\r\n'
                  b'Content-Length: 9001\r\n'
                  b'Expect: 100-continue\r\n'
                  b'\r\n')
assert isinstance(conn.next_event(), h11.Request)
```

But we decide we don’t want to handle it:

```
conn.send(h11.Response(status_code=403,
                       headers=[]))
conn.send(h11.EndOfMessage())
```

The only sensible thing for the client to do in this situation is to close the connection:

```
conn.receive_data(b'')
conn.next_event()
```

But that gives us:

```
h11._util.RemoteProtocolError: peer closed connection without sending complete message body (received 0 bytes, expected 9001)
```

This is not a protocol error, this is exactly what the 100-continue dance was designed for.

I’m not sure what is the right thing to do here. Maybe the current behavior is a good simplification. Or maybe h11 could accept the `ConnectionClosed` event from the client when `our_state in [h11.SEND_BODY, h11.DONE]`.

**Comment by njsmith** [comment]
Hmm, yeah, interesting point.

In a sense it is a protocol error, or at least as much as any connection drop during the middle of a request/response cycle – you're allowed to do it (who could stop you), but it does mean that the request was incomplete and should be treated differently than a complete request. The way the spec is written is pretty awkward – 100-continue doesn't actually change HTTP's body framing semantics. If you want to keep the connection up and re-use it then you still have to send the whole body, even if you got an early error; btw you should probably be sending `connection: close` on your early errors. It just gives the client a hint that they should maybe take advantage of their option of ungracefully aborting the connection. Not that this means we can't handle it more gracefully because like you say it's expected in practice, but it's not 100% obvious :-).

I'm leaning towards leaving things as is, because I think that in general you probably do want to treat a half-sent rejected request similarly to how you'd treat a half-sent acceptable request, and in particular I am nervous about acting like the whole body corresponding to those headers was sent, when it actually wasn't? But I'll leave this open for now to ponder some more or in case anyone else wants to jump in...

**Comment by Lukasa** [comment]
I think the current behaviour is exactly right. If we let section 5.1.1 of RFC 7231 be our guide:

> A server that responds with a final status code before reading the entire message body SHOULD indicate in that response whether it intends to close the connection or continue reading and discarding the request message (see Section 6.6 of [RFC7230]).

That is, the client is clearly allowed to keep sending the request if the server hasn't indicated that it will close the connection, and so failing to do so must cause an error condition in the server so that it knows that the framing is busted.

**Comment by njsmith** [comment]
Well, we do raise the same error regardless of whether we sent connection:
close...

**Comment by Lukasa** [comment]
So for connection: close you could make the argument that this shouldn't be an error, but frankly at this point you need to decide how you want to complicate the event structure. Essentially, your users would need to tolerate the possibility of getting EOF before getting a EOM for the request, and would need to know that that means the client terminated early *and* that it's not an error. 

I suppose you could create a new event for this?

**Comment by Nikratio** [comment]
<rant>Any client implementation following RFC 7231 is stupid. The whole point of Expect-continue is to avoid wasting time + bandwidth if the server will return an error. A client that is going to send the data anyway shouldn't have bothered with Expect: 100-continue in the first place. Forcing a re-connect isn't much better. The situation is a somewhat better when using Chunked Encoding, since the client could reasonably send an empty chunk. But that means the encoding now determines sequencing of transmit/receive operations, which is pretty awful too. HTTP sucks. </rant>

In controlled conditions (i.e., server and client under my control), I am currently solving the problem by recreating the Connection object, but that still leaves me with state == IDLE rather than state == DONE, and thus results in an error when cycling the connection unconditionally. I think it would be great if h11 offered a way to forcefully set client+server state to DONE, so that one can take full advantage of expect100 where possible.

**Comment by njsmith** [comment]
I'm not going to argue that HTTP doesn't suck :-). But there is a reason they did things this way, which is backcompat. In general a client doesn't know whether the server they're talking to understands `expect: 100-continue`. So clients that use it need some timeout where if they haven't seen a 100 or 4xx response after a bit, they assume that they're talking to an old server and start sending data anyway. But this timeout could also happen with a server that does understand `expect: 100-continue`just due to network conditions or something. So if you're a server that understands `expect: 100-continue`, and sends back an early 4xx, and then gets some more data on that connection... You have no way to know whether that's the start of a new request, or whether it's part of the body of the old request, sent by the client's timeout logic. So the spec'ed behavior is the only way to keep protocol parsing unambiguous under the constraints of backcompat.

Anyway, your "controlled conditions" hack is clever and can work because your client knows for sure that the server understands `expect: 100-continue`, but now you're really using your own non-standard http-like protocol that doesn't interoperate with real http clients or servers. I'm not interested in adding hooks to h11 just to implement idiosyncratic non-http protocols like this.

The official solution to your issue is to use HTTP/2, of course. Or live with a whole extra 2 lines of code to check for IDLE/IDLE before calling `start_next_cycle` :-).

**Comment by njsmith** [comment]
Looks like the conclusion here is to keep things the way they are.
