### ISSUE TITLE
Confusing absence of response in client state diagram

### ISSUE THREAD

**Issue by Nikratio** [python-hyper/h11#51]
Hi,

First, thanks for writing h11! I'd like to use HTTP with curio, and it will save me a lot of time!

It seems to me that there is something wrong with the client state diagram in the documentation. According to the diagram, I think the client out to be able to continously send requests without ever receiving a response - but later on, you explicitly say that h11 doesn't support pipelining in the client. So I think there state diagram misses a few states related to reading the response from the server.

**Comment by njsmith** [comment]
In the diagram, the only way for the client to get back to `IDLE` is the arc labeled `start_next_cycle`. That's a special method call [documented here](https://h11.readthedocs.io/en/latest/api.html#h11.Connection.start_next_cycle), which is only allowed if the client and server are *both* in the `DONE` state. So that's how we enforce synchronization.

Note that h11 *always* tracks that whole state diagram – client machine, server machine, and the 3 little ancillary machines – even though in any particular case it's only responsible for the client, or only responsible for the server. When it's in client mode, the client diagram keeps track of what you're allowed to do, and the server diagram keeps track of what it's seen from the remote peer and what it's expecting to see next. So both of them in `DONE` means that we've sent a full request, and then we've seen a full response. And then when h11 is in server mode, of course, this is all reversed. Does that make sense?

BTW, if you're interested in curio, you might also want to check out trio. I'm probably not the most unbiased judge, given that I wrote it, but it's intended as a kind of next generation library inspired by the things I felt curio did well and where it struggled, and with more attention towards being generally usable (e.g. we try to deprecate things instead of just changing them).

**Comment by Nikratio** [comment]
Thanks for the explanations! It does make sense now, but I think the diagram is nevertheless confusing :-). Maybe it would help to somehow indicate in the diagram that start_next_cycle() depends on the peer state...

**Comment by Nikratio** [comment]
I had a look at trio, and it might be a better choice indeed. But what I am missing most is a simple list of the differences to curio - it's very difficult to pierce this together from the documentation if you are not very familiar with either project yet..

**Comment by njsmith** [comment]
@Nikratio Unfortunately as the author it's very difficult to give a useful comparison table, both because I'm so close to things that I don't know what's relevant to you, and because that kind of article tends to turn into us-vs-them nitpicking – so I'm sort of hoping that others will write those posts :-).

This comment might help give some sense of why trio exists: https://github.com/dabeaz/curio/issues/35#issuecomment-358251117

**Comment by njsmith** [comment]
Just re-read this and I'm not thinking of any concrete changes we could make to improve things, so closing. We can re-open or create a new issue if anyone has new ideas in the future.
